Update zhTW
zarillion/handynotes-plugins pull request #41
Opened 2020-11-16 17:35 UTC by BlueNightSky

Roll back some translations and add new content.

2020-11-16 17:46 UTC, dmartinzar commented
@mcc1 I'll let you decide whether this is good to merge. @BlueNightSky I know you are already in our Discord from the previous plugin, @mcc1 the link is here if you want to discuss in the #translators channel: https://discord.gg/EXCcmYW

2020-11-16 17:48 UTC, zarillion commented
@mcc1 I'll let you decide whether this is good to merge. @BlueNightSky I know you are already in our Discord from the previous plugin, @mcc1 the link is here if you want to discuss in the #translators channel: https://discord.gg/EXCcmYW

2020-11-17 03:57 UTC, mcc1 commented on plugins/09_Shadowlands/localization/zhTW.lua
> +L["mymaen_note"] = "擊殺區域內的腐楠精靈直到他做出表情並出現。"
```suggestion
L["mymaen_note"] = "擊殺區域內的腐棘精靈直到他做出表情並出現。"
```

2020-11-17 04:33 UTC, mcc1 requested changes
update some translation. Thanks @adavak provide more data

2020-11-17 04:33 UTC, mcc1 commented on plugins/09_Shadowlands/localization/zhTW.lua
> +L["icecrown_rares"] = "所有首領以固定的順序每20分鐘刷新一個。每個可以一天被拾取多次！"
```suggestion
L["icecrown_rares"] = "所有首領以固定的順序每10分鐘刷新一個。每個可以一天被拾取多次！"
```

2020-11-17 04:33 UTC, mcc1 commented on plugins/09_Shadowlands/localization/zhTW.lua
> +L["prepatch_intro"] = "完成暗影之境前夕事件指引任務解鎖此區域的稀有。"
```suggestion
L["prepatch_intro"] = "完成暗影之境前夕事件前置任務解鎖此區域的稀有。"
```

2020-11-17 04:33 UTC, mcc1 commented on plugins/09_Shadowlands/localization/zhTW.lua
> +L["sanngror_note"] = "如果他是不可攻擊，等待直到他不再靈魂實驗。"
```suggestion
L["sanngror_note"] = "如果他是不可攻擊，等待直到他不再對靈魂做實驗。"
```

2020-11-17 04:33 UTC, mcc1 commented on plugins/09_Shadowlands/localization/zhTW.lua
> +L["inquisitor_note"] = "把100個 {currency:1816} 交給 {npc:160248} 有機會獲得此罪碑。"
```suggestion
L["inquisitor_note"] = "把100個 {currency:1816} 交給 {npc:160248} 有機會獲得此罪孽石。"
```

2020-11-17 04:33 UTC, mcc1 commented on plugins/09_Shadowlands/localization/zhTW.lua
> +L["high_inquisitor_note"] = "把250個 {currency:1816} 交給 {npc:160248} 有機會獲得此罪碑。"
```suggestion
L["high_inquisitor_note"] = "把250個 {currency:1816} 交給 {npc:160248} 有機會獲得此罪孽石。"
```

2020-11-17 04:33 UTC, mcc1 commented on plugins/09_Shadowlands/localization/zhTW.lua
> +L["grand_inquisitor_note"] = "把10個 {item:180451} 交給 {npc:160248} 有機會獲得此罪碑。"
```suggestion
L["grand_inquisitor_note"] = "把10個 {item:180451} 交給 {npc:160248} 有機會獲得此罪孽石。"
```

2020-11-17 04:33 UTC, mcc1 commented on plugins/09_Shadowlands/localization/zhTW.lua
> +L["smuggled_cache_note"] = ns.color.Red("*在拾取之前*：").."確認已完成 {quest:60480} 分支任務否則寶藏和任務將缺少40個 {currency:1820}。"
```suggestion
L["smuggled_cache_note"] = ns.color.Red("*在拾取之前*：").."請確認已完成 {quest:60480} 支線任務否則寶藏和任務將缺少40個 {currency:1820}。"
```

2020-11-17 04:33 UTC, mcc1 commented on plugins/09_Shadowlands/localization/zhTW.lua
> +快看！{spell:343124}！勇敢的冒險家快過去，這肯定不是詭計。等一下，那是卡拉贊的音樂嗎？{npc:174663} 在這裡干嘛…？
```suggestion
快看！{spell:343124}！勇敢的冒險家快過去，這肯定不是詭計。等一下，那是卡拉贊的音樂嗎？{npc:174663} 在這裡幹嘛…？
```

2020-11-17 04:33 UTC, mcc1 commented on plugins/09_Shadowlands/localization/zhTW.lua
> +轉化後，到 {npc:158406} 平台（入口在東側）下面洞穴並點擊管道傳送寶箱。
```suggestion
轉化後，到 {npc:158406} 平台（入口在東側）下面洞穴並點擊管線來傳送到寶箱。
```

2020-11-17 04:33 UTC, mcc1 commented on plugins/09_Shadowlands/localization/zhTW.lua
>  L["blackhound_cache"] = "黑犬寶箱"
```suggestion
L["blackhound_cache"] = "黑犬儲物箱"
```

2020-11-17 09:52 UTC, merged